name: AutoCheck

on:
  workflow_dispatch:
  push:
  pull_request:
  watch:
    types: [ started ]
  schedule:
    - cron: 45 */10 * * *

jobs:
  healthcheck:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Sync with upstream
      if: github.repository != 'Dimlitter/zju-dailyhealth-autocheck'
      continue-on-error: true
      uses: aormsby/Fork-Sync-With-Upstream-action@v3.2
      with:
        upstream_sync_repo: Dimlitter/zju-dailyhealth-autocheck
        upstream_sync_branch: main
        target_sync_branch: main
        target_repo_token: ${{ secrets.GITHUB_TOKEN }}
        upstream_pull_args: '-s recursive -Xtheirs'
        
    - name: 'Set python'
      uses: actions/setup-python@v1
      with:
          python-version: '3.8'
    - name: 'Install dependencies'
      run: python3 -m pip install --upgrade pip

    - name: 'install libs'
      run: pip3 install requests && pip install ddddocr

    - name: StartCheck
      env:
       account: ${{ secrets.account }}
       password: ${{ secrets.password }}
       TG_TOKEN: ${{ secrets.TG_TOKEN }}
       CHAT_ID: ${{ secrets.CHAT_ID }}
       lng: ${{ secrets.lng }}
       lat: ${{ secrets.lat }}
       DD_BOT_TOKEN: ${{ secrets.DD_BOT_TOKEN }}
       DD_BOT_SECRET: ${{ secrets.DD_BOT_SECRET }}
       REMINDERS: ${{ secrets.REMINDERS }}
       
      run: python3 check.py
